### PR TITLE
Add Insurello to the list

### PR DESCRIPTION
**Pull request by Mousaka**
PR for Testimonial https://github.com/fsharp/fsfoundation/pull/918

### CODE REVIEW

**Comment by dsyme** [comment]
@Mousaka Could you also add a testimonial to https://fsharp.org/testimonials please?  By doing that it helps us verify the addition here. Thanks

**Comment by Mousaka** [comment]
Will do! Later today though :)

**Comment by Mousaka** [comment]
@dsyme [PR](https://github.com/fsharp/fsfoundation/pull/918) for testimonial has been added!

**Review by Kavignon — APPROVED** [review]
Thank you for your contribution and the testimonial! Cheers!

**Pull request merged**
