### PR TITLE
Add Lula to list

### PR DESCRIPTION
**Pull request by lulamccarty**

### CODE REVIEW

**Comment by dsyme** [comment]
@lulamccarty Could you also add a testimonial to https://fsharp.org/testimonials please?  By doing that it helps us verify the addition here. Thanks

**Comment by lulamccarty** [comment]
> @lulamccarty Could you also add a testimonial to https://fsharp.org/testimonials please? By doing that it helps us verify the addition here. Thanks

Will do!

**Comment by lulamccarty** [comment]
The testimonial PR is available at https://github.com/fsharp/fsfoundation/pull/917

**Review by Kavignon — APPROVED** [review]
LGTM! Sorry, this took so long and thanks for also doing the testimonial!

**Pull request merged**
